# Generated by Django 3.1.7 on 2021-04-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210330_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=200)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
