# Generated by Django 3.1.7 on 2021-04-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210407_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('cat', 'Gato'), ('dog', 'Perro')], max_length=10, null=True),
        ),
    ]
